[package]
name = "basic-polylux"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Andreas Kröpelin"]
license = "MIT"
description = "Starter template for Polylux"
homepage = "https://github.com/polylux-typ/basic"
repository = "https://github.com/polylux-typ/basic"
keywords = ["basic", "getting started", "polylux", "presentation"]
categories = ["presentation"]

[template]
path = "template"
entrypoint = "slides.typ"
thumbnail = "thumbnail.png"
